#!/bin/sh

if [[ ! -z $(grep "DEBUG=yes" config) ]]; then
  DEBUG=yes
fi

if [[ -d rootfs ]] && [[ $DEBUG != yes ]]; then
  echo "mikulinux exists"
  exit 1
fi

if [ ! $EUID -ne 0 ]; then
  echo "please don't run as root"
  exit 1
fi

if ! ./scripts/deps; then
  exit 1
fi

echo "######## Miku Linux ########" & sleep 1

if [[ ! -d rootfs ]]; then
 ./scripts/rootfs
fi

cp -rf pkg rootfs/pkg
cp -rf src/* rootfs

[[ ! -z $@ ]] && exit 0

export ROOT=$PWD/rootfs

./scripts/install_pkg base

if [[ $DEBUG = yes ]]; then
  exit 0
fi

if ! $(./nono -e base); then
  echo "failed to build mikulinux"
  exit 1
fi

cp nono rootfs/bin
cp config rootfs/src

echo "wanna make iso? (y/n)"
read -s -t 69 -n 1 answer

if [ $? != 0 ]; then
  echo "timeout"
elif [ $answer = y ]; then
  ./scripts/iso
else
  echo "ok."
fi