#!/bin/sh

if [ -d out ]; then
  cp src/bin/nono out/bin/nono
  cp -rf src/* out
  cp -rf pkg/* out/src/pkg
  cd out/bin
  ./nono -i base
  cd ../../
  exit 0
fi

mkdir out
cd out

mkdir -p bin boot dev etc home lib mnt proc opt root share srv src sys tmp var
mkdir -p src/build src/dl src/pkg src/work

touch src/pkgs

ln -sfn . usr
ln -sfn bin sbin

chmod 1777 tmp
chmod 700 root

cp -rf ../src/* .
cp -rf ../pkg/* src/pkg

cd bin
./nono -i base
