#!/bin/sh

if [ ! $EUID -ne 0 ]; then
  echo "please don't run as root"
  exit 1
fi

WORK=$PWD

if ! ./scripts/deps; then
  exit 1
fi

./scripts/rootfs $WORK

cp nono rootfs/bin

export ROOT=$WORK/rootfs
./nono -i base

if ! $(./nono -e base); then
  echo "failed to build mikulinux"
  exit 1
fi

echo "wanna make iso? (y/n)"
read -s -t 69 -n 1 answer

if [ $? != 0 ]; then
  echo "timeout"
elif [ $answer = y ]; then
  ./scripts/iso $WORK
else
  echo "ok."
fi