#!/bin/sh

die() {
  echo $1
  exit 1
}

if [[ ! -d out ]]; then
  die "out directory doesn't exist"
fi

cd out/bin

if [[ ! -d ../lib/syslinux ]]; then
  ./nono -i syslinux

  if [[ ! -d ../lib/syslinux ]]; then
    die "syslinux is failed to build"
  fi
fi

if [[ ! -e ../boot/initrd.img ]]; then
  ./nono -i initramfs

  if [[ ! -e ../boot/initrd.img ]]; then
    die "initramfs is failed to create"
  fi
fi

if [[ ! -e ../boot/vmlinuz ]]; then
  ./nono -i kernel

  if [[ ! -e ../boot/vmlinuz ]]; then
    die "kernel is failed to build"
  fi
fi

cd ../..

EXCLUDE="src/dl src/build"

ISOROOT=$(mktemp -d)

cp out/lib/syslinux/bios/ldlinux.c32 out/boot
cp out/lib/syslinux/bios/isolinux.bin out/boot
cp out/lib/syslinux/bios/isohdpfx.bin out/boot

cp -r out/boot/* $ISOROOT

FAKEROOT=$(mktemp -d)
mkdir $FAKEROOT/boot $FAKEROOT/proc $FAKEROOT/sys $FAKEROOT/dev $FAKEROOT/tmp $FAKEROOT/mnt

mksquashfs out/bin out/etc out/include out/lib out/opt out/root out/sbin out/share out/src out/srv out/usr out/var $FAKEROOT/* $ISOROOT/rootfs.img -e $EXCLUDE

xorriso \
  -as mkisofs \
  -o mikulinux.iso \
  -b isolinux.bin \
  -isohybrid-mbr $ISOROOT/isohdpfx.bin \
  -c boot.cat \
  -no-emul-boot \
  -iso-level 2 \
  -boot-load-size 4 \
  -boot-info-table $ISOROOT
