#!/bin/sh

die() {
  echo "$@"
  exit 1
}

if [[ ! -e /bin/qemu-system-x86_64 ]]; then
  die "no qemu found"
fi

if [[ ! -e mikulinux.iso ]]; then
  die "mikulinux iso not found"
fi

qemu-system-x86_64 -boot d -cdrom mikulinux.iso -m 512