#!/bin/sh

if [[ -d rootfs ]]; then
  cp -rf src/* rootfs
  exit 0
fi

mkdir rootfs
cd rootfs

mkdir -p bin dev etc home lib mnt proc opt root share srv src sys tmp var
mkdir -p src/build src/dl src/work

touch pkgs

ln -sfn . usr
ln -sfn bin sbin

chmod 1777 tmp
chmod 700 root

mknod dev/null c 1 3
mknod dev/zero c 1 5
mknod dev/tty  c 5 0
mknod dev/random c 1 8
mknod dev/urandom c 1 9

chmod 0666 dev/{null,tty,zero}
chown root.tty dev/tty

cp -rf ../src/* .