#!/bin/sh

mkdir -p rootfs
cd rootfs

mkdir -p dev etc home mnt proc opt root share srv src sys tmp usr var
mkdir -p usr/bin usr/lib
mkdir -p src/build src/dl

touch pkgs

ln -s usr/bin bin
ln -s usr/bin sbin

ln -s usr/lib lib
ln -s usr/lib lib64

cd usr

ln -s bin sbin
ln -s lib lib64

cd ..

chmod 1777 tmp
chmod 700 root